thrift:
  server:
    ip: 192.168.30.1
    syn:
      port: 9047
    asyn:
      port: 9147
gov:
  sequarius:
    docker_center:
      file_path: config
      log_path: /var/lib/docker/containers
logging:
  level:
    root: info
    gov.sequarius: debug